Use apply instead of create
openshift-cnv/cnv-ci pull request #67
Opened 2023-09-28 09:54 UTC by rabin-io

This should allow the code to run if we already have applied the ICSP in a different stage (like in other workflows).

Signed-off-by: Rabin Yasharzadehe <rabin@rabin.io>

2023-09-28 10:01 UTC, dhiller requested changes

2023-09-28 10:01 UTC, dhiller commented on hack/set-imagecontentsourcepolicy.sh
>  echo "creating imageContentSourcePolicy"
```suggestion
echo "applying imageContentSourcePolicy"
```

2023-09-28 10:05 UTC, dhiller commented
/ok-to-test

2023-09-28 10:06 UTC, dhiller approved these changes
/approve

2023-09-28 10:39 UTC, tiraboschi approved these changes

2023-09-28 20:38 UTC, rabin-io commented
/test 4.13-e2e-deploy

2023-09-28 21:03 UTC, tiraboschi commented
/lgtm

2023-09-28 21:03 UTC, tiraboschi commented
/retest

2023-10-01 01:37 UTC, rabin-io commented
/retest

2023-10-01 07:44 UTC, rabin-io commented
/test 4.13-e2e-deploy

2023-10-01 10:26 UTC, rabin-io commented
Any reason to delay the merge because of the above failed jobs?

```
level=error msg=Error: creating Linux Virtual Machine: (Name "ci-op-xd78n623-dc7cb-tcw2s-master-0" / Resource Group "ci-op-xd78n623-dc7cb-tcw2s-rg"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status= Code="SkuNotAvailable" Message="The requested size for resource '/subscriptions/62ff73f0-1c1b-427c-afda-8d027aa162cd/resourceGroups/ci-op-xd78n623-dc7cb-tcw2s-rg/providers/Microsoft.Compute/virtualMachines/ci-op-xd78n623-dc7cb-tcw2s-master-0' is currently not available in location 'eastus2' zones '2' for subscription '62ff73f0-1c1b-427c-afda-8d027aa162cd'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details."
```

2023-10-02 07:24 UTC, merged

2023-10-02 07:24 UTC, tiraboschi commented
> Any reason to delay the merge because of the above failed jobs?

Forcing merge